package SwingPackage;

/**
 *
 * @author USER
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_MemberInfo = new javax.swing.JButton();
        jButton_TrainerInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 41, 61, 34);

        jButton_MemberInfo.setBackground(new java.awt.Color(0, 204, 51));
        jButton_MemberInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_MemberInfo.setText("MEMBERS INFORMATION");
        jButton_MemberInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MemberInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_MemberInfo);
        jButton_MemberInfo.setBounds(204, 149, 230, 50);

        jButton_TrainerInfo.setBackground(new java.awt.Color(0, 153, 0));
        jButton_TrainerInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_TrainerInfo.setText("TRAINERS INFORMATION");
        jButton_TrainerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TrainerInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_TrainerInfo);
        jButton_TrainerInfo.setBounds(204, 255, 230, 48);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_MemberInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MemberInfoActionPerformed
        Members mem=new Members();
             mem.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jButton_MemberInfoActionPerformed

    private void jButton_TrainerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TrainerInfoActionPerformed
       Trainers train=new Trainers();
       train.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton_TrainerInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_MemberInfo;
    private javax.swing.JButton jButton_TrainerInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}